const params = new URLSearchParams(window.location.search);
const produtoId = params.get('id');
const produtos = [
    { id: 1, nome: 'Fettucine Alfredo', descricao: 'Preparado com massa fresca, envolta em um luxuoso molho de creme de leite, manteiga e parmesão envelhecido. Finalizado com um toque de noz-moscada e pimenta-do-reino moída na hora, a perfeita combinação de cremosidade e sabor sofisticado, proporcionando uma experiência gastronômica inesquecível.', preco: 80.0, imagem: 'src/imagens/dishes-png/full/fettuccine-alfredo-removebg-preview.png', ingredientes: 'Fettucine, Manteiga, Queijo Parmesão, Pimenta preta, Noz-moscada.', origem:'O Fettuccine Alfredo nasceu nos salões culinários de Roma, criado pelo chef Alfredo di Lelio como um gesto de amor para sua esposa. Desde então, este prato emblemático se tornou um símbolo global de elegância e tradição culinária italiana.'},

    { id: 2, nome: 'Pasta alla Bolognese', descricao: 'Nosso macarrão à bolonhesa é uma experiência gastronômica que combina massa artesanal al dente com um suculento ragu de carne bovina selecionada, tomates frescos, cebolas caramelizadas e um toque de vinho tinto. Finalizado com lascas de parmesão envelhecido e ervas aromáticas, é uma celebração de sabores autênticos e sofisticados.', preco: 100.00, imagem: 'src/imagens/dishes-png/full/bolognese-1-removebg-preview.png', ingredientes:'Tagliatelle, Ragú de Carne Bovina/Suína, Tomates Frescos, Cebola Caramelizada, Vinho Tinto, Parmesão, Ervas Aromáticas.', origem:'A bolonhesa tem suas raízes nos palácios gastronômicos de Bolonha, Itália, onde foi criado o "ragù alla bolognese" no século XVIII. Este ragu de carne bovina, cozido lentamente com tomates frescos, cebolas caramelizadas e vinho tinto, tornou-se um ícone da alta culinária italiana, celebrando sabores autênticos e uma tradição centenária. ' },
    
    { id: 3, nome: 'Pasta alla Carbonara', descricao: 'Nosso Spaghetti alla Carbonara é um verdadeiro deleite da cozinha romana. Feito com espaguete al dente, é envolvido em um creme sedoso de gemas de ovos frescos e queijo pecorino romano. Acrescentamos pancetta crocante e um toque generoso de pimenta-do-reino moída na hora, criando uma harmonia perfeita de sabores ricos e autênticos. Uma experiência culinária refinada e inesquecível.', preco: 120.00, imagem: 'src/imagens/dishes-png/full/pasta-carbonara-removebg-preview.png', ingredientes:'Spaghetti, Ovos, Queijo Pecorino Romano, Pancetta, Pimenta Preta.', origem:'O Carbonara tem origens humildes nas ruas de Roma, Itália, onde foi criado como um prato reconfortante pelos trabalhadores do carvão (carbonai). Esta receita simples e deliciosa combina massa cozida al dente com um molho sedoso feito de ovos batidos, queijo Pecorino Romano, pancetta crocante e pimenta preta moída. O Carbonara continua a encantar paladares ao redor do mundo, sendo uma celebração da simplicidade e do sabor autêntico da cozinha italiana.' },

    { id: 4, nome: 'Tiramisù', descricao: 'Nosso Tiramisù é uma sobremesa italiana clássica, elaborada com camadas delicadas de biscoitos savoiardi embebidos em café expresso, intercalados com um creme suave de mascarpone e ovos frescos. Finalizado com uma generosa pitada de cacau em pó e raspas de chocolate amargo, oferece uma combinação perfeita de sabores e texturas, proporcionando um final sublime para sua refeição.', preco: 50.00, imagem: 'src/imagens/dishes-png/full/old-school-tiramisu-removebg-preview.png', ingredientes:'Biscoito Savoiardi, Café Expresso, Creme Mascarpone, Cacau em Pó, Chocolate', origem:' O Tiramisu, tem suas raízes na região de Veneto, particularmente associada à cidade de Treviso. Criada como uma evolução refinada de receitas tradicionais do final do século XX, conhecido por seu nome que significa "levanta-me", o Tiramisu não apenas satisfaz o paladar, mas também encanta como um ícone da doçura e sofisticação da cozinha italiana.' },

    { id: 5, nome: 'Ragú de porco', descricao: 'Nosso Ragu de Porco com Polenta Cremosa é um prato que harmoniza sabores rústicos e refinados. O ragu é preparado com carne de porco cozida lentamente em um molho rico de tomates e ervas. A polenta, incrivelmente cremosa, complementa o ragu de forma perfeita. Finalizado com parmesão e ervas frescas, é uma experiência gastronômica inesquecível.', preco: 72.50, imagem: 'src/imagens/dishes-png/full/ragu-de-porco.png', ingredientes:'Carne de Porco, Tomate, Ervas Finas, Polenta, Parmesão.', origem:'O Ragú de porco com polenta tem suas raízes nas cozinhas rurais do norte da Itália, especialmente em Emilia-Romagna e Lombardia. Este prato robusto reflete a tradição de aproveitar os ingredientes locais, traduzindo-se em uma celebração da simplicidade e do sabor regional, combina camadas de texturas e sabores que capturam a essência da culinária italiana.'},

    { id: 6, nome: 'Salada Caprese ', descricao: 'Nossa Salada Caprese é uma celebração da simplicidade e frescor. Tomates maduros, mussarela de búfala e folhas de manjericão são harmoniosamente dispostos e regados com azeite extra virgem e um toque de balsâmico. Finalizada com uma pitada de flor de sal e pimenta-do-reino moída na hora, esta salada oferece um equilíbrio perfeito de sabores frescos e aromáticos. Perfeita como entrada leve e sofisticada.', preco: 40.00, imagem: 'src/imagens/dishes-png/full/salada-caprese.png', ingredientes:'Tomate, Mussarela de Búfala, Manjericão, Azeite Extra Virgem, Balsâmico.', origem:'A Salada Caprese tem origens na ilha de Capri, no Golfo de Nápoles, Itália. Este prato simples e sofisticado captura a essência da culinária mediterrânea com seus ingredientes frescos e cores vibrantes, celebra a harmonia entre o frescor dos ingredientes locais e a simplicidade elegante da gastronomia italiana.'},
    
    { id: 7, nome: 'Berinjela à Parmigiana ', descricao: 'Nossa Melanzane alla Parmigiana é um clássico reconfortante da culinária italiana. Camadas de berinjela perfeitamente grelhada são intercaladas com um rico molho de tomate, mussarela derretida e parmesão ralado. Assada até borbulhar, cada fatia oferece uma combinação harmoniosa de sabores e texturas. Finalizada com manjericão fresco, é uma verdadeira celebração da tradição italiana.', preco: 57.50, imagem: 'src/imagens/dishes-png/full/BAs-best-eggplant-parmesan-removebg-preview.png', ingredientes:'Berinjela, Molho de Tomate, Mussarela, Parmesão.', origem:'Originária da região da Emilia-Romagna na Itália, reflete sua história humilde como um prato camponês tradicional. Surgiu como uma forma criativa de utilizar a berinjela abundante da região. Hoje, é reverenciada não apenas por sua técnica cuidadosa e camadas de sabores ricos, mas também por seu papel como um ícone da culinária italiana, que une tradição e elegância de maneira cativante.' },

    { id: 8, nome: 'Lasanha de Espinafre', descricao: 'Nossa Lasanha de Espinafre com Ricota é uma experiência gastronômica sublime. Camadas de massa fresca são intercaladas com um recheio cremoso de espinafre refogado e ricota fresca, complementadas por um molho de tomate encorpado. Assada até dourar, cada garfada revela uma combinação perfeita de sabores e texturas. Uma opção deliciosamente reconfortante para os amantes da culinária italiana.', preco: 65.00, imagem: 'src/imagens/dishes-png/full/spinach-ricotta-lasagna-lede-removebg-preview.png', ingredientes:'Massa Fresca, Espinafre, Ricota, Molho de Tomate.', origem:'Enraizada na tradição culinária italiana da Toscana e Emilia-Romagna, começou como um prato reservado para ocasiões especiais, destacando-se pela meticulosidade na preparação. Ao adicionar espinafre fresco e ricota à receita clássica de lasanha ao longo dos séculos, surgiram novas camadas de sabor e textura, elevando-a a um ícone de celebração gastronômica. Hoje, continua a ser apreciada não apenas por seu sabor refinado, mas também por sua história enriquecedora da mesa italiana.' },

    { id: 9, nome: 'Panna Cotta', descricao: 'Nossa Panna Cotta é uma sobremesa elegante e irresistível. Feita com creme de leite fresco, açúcar e essência de baunilha, é delicadamente moldada e servida com uma geleia de frutas vermelhas frescas. Sua textura sedosa e sabor suave tornam cada colherada uma verdadeira indulgência. Um final perfeito para uma refeição memorável.', preco: 35.00, imagem: 'src/imagens/dishes-png/full/panna-cotta.png', ingredientes:'Creme de Leite Fresco, Açúcar, Essência de Baunilha, Geleia de Frutas Vermelhas.', origem:'Originária como um prato caseiro na região do Piemonte, a Panna Cotta ganhou popularidade ao longo dos anos, tornando-se um clássico da culinária italiana apreciado por sua suavidade e versatilidade na combinação com diversas coberturas, como frutas frescas ou caldas.'},

    { id: 10, nome: 'Tomate Confit', descricao: 'O tomate confit é uma iguaria que eleva o sabor dos tomates a outro patamar. Tomates maduros são lentamente assados em baixa temperatura com azeite de oliva, alho e ervas aromáticas, resultando em um sabor concentrado e delicadamente caramelizado. Este processo realça a doçura natural dos tomates, criando um acompanhamento versátil e delicioso para diversos pratos.', preco: 40.00, imagem: 'src/imagens/dishes-png/full/tomate-confit.png', ingredientes:'Tomate, Azeite, Alho, Ervas Aromáticas.', origem:'Embora, a receita tenha suas raízes na parte provençal, sul da França, é uma receita muito difundida em diversas partes do mundo, em especial na culinária italiana, sendo uma técnica amplamente utilizada por grandes chefes do país da bota.'},

    { id: 11, nome: 'Gnudi de Ricota', descricao: 'Nossos Gnudi de Ricota ao Pomodoro são uma experiência culinária requintada. Feitos com ricota fresca, espinafre e uma pitada de noz-moscada, são delicadamente cozidos e servidos com um molho de tomate caseiro, preparado com tomates maduros, alho e manjericão fresco. Cada mordida é uma explosão de sabores suaves e frescos, em uma combinação que encanta os paladares mais exigentes.', preco: 75.00, imagem: 'src/imagens/dishes-png/full/ricotta-gnudi.png' , ingredientes:'Ricota Fresca, Espinagre, Noz-Moscada, Mlolho de Tomate, Alho, Manjericão.', origem:'Originários da pitoresca Toscana na Itália, refletem uma tradição culinária que valoriza a simplicidade e a qualidade dos ingredientes locais. Derivados dos tradicionais Gnudi, revelam uma evolução histórica desde suas raízes camponesas até serem apreciados por sua textura suave e sabor refinado. Hoje, são um testemunho da habilidade artesanal italiana, destacando-se pela harmonia entre tradição e inovação na cozinha regional.'},
    
    { id: 12, nome: 'Ribollita', descricao: 'A Ribollita do nosso restaurante combina ingredientes frescos e selecionados, como feijão branco cremoso, legumes orgânicos e pão rústico. Cozida em um caldo rico, cada garfada revela sabores complexos ressaltados por ervas frescas e azeite de oliva. Uma interpretação requintada deste clássico da culinária toscana.', preco: 55.00, imagem: 'src/imagens/dishes-png/full/riolita.png', ingredientes:'Feijão Branco, Legumes, Pão Rústico, Ervas Frescas, Azeite de Oliva.', origem:'A Ribollita, originária da pitoresca Toscana, na Itália, é uma sopa que destaca a tradição culinária de aproveitar ingredientes simples de forma criativa. Surgiu como uma solução inteligente para reaproveitar sobras de pão e vegetais. Ao longo dos séculos, a Ribollita transformou-se de uma refeição humilde de camponeses em um prato apreciado pela sua substância nutritiva e pela capacidade de melhorar seu sabor com o tempo, refletindo assim a rica herança gastronômica e a valorização da sustentabilidade na cozinha toscana.'},
    
  ];
const produto = produtos.find(p => p.id == produtoId);
const contadorCarrinho = document.querySelector('#contador-carrinho');
  
let carrinhoCount = 0;

if (produto) {

  const container = document.querySelector('#detalhes-produto');
  container.className='container' 
  const descricao = document.createElement('div');
  descricao.className='descricao'
  const banner = document.createElement('div');
  banner.className='imagem'
  container.appendChild(banner);
  container.appendChild(descricao);
 
  descricao.innerHTML=` <h1>${produto.nome.toUpperCase()}</h1> <br>
  <p>${produto.descricao}</p>
  <br>
  <h3>INGREDIENTES:</h3>
  <p class='ingredientes'>${produto.ingredientes}</p>
  <br> <br>
  <h3>ORIGEM DO PRATO:</h3>
  <p class='origem'>${produto.origem}</p>


  
 `
 banner.innerHTML=`
  <img src="${produto.imagem}" alt="${produto.nome}"> 
 `
} else {
  document.querySelector('#detalhes-produto').textContent = 'Produto não encontrado';
}